version: '2'
services:
    orderprocessorproject-postgresql:
        image: postgres:10.4
        # volumes:
        #     - ~/volumes/jhipster/orderProcessorProject/postgresql/:/var/lib/postgresql/data/
        environment:
            - POSTGRES_USER=orderProcessorProject
            - POSTGRES_PASSWORD=
        ports:
            - 5432:5432
